name: "tire_quality_classifier"
backend: "onnxruntime"
max_batch_size: 4

input [
    {
        name: "IMAGES"
        data_type: TYPE_FP32
        dims: [ -1, 3, 150, 150 ]
    }
]

output [
    {
        name: "CLASS_PROBS"
        data_type: TYPE_FP32
        dims: [ -1, 2 ]
    }
]
instance_group [ { count: 4 }]
optimization { execution_accelerators {
    cpu_execution_accelerator : [ {
      name : "openvino"
    }]
  }}
dynamic_batching {
    # preferred_batch_size: 4
    # max_queue_delay_microseconds: 200
}
